# -*- coding: utf-8 -*-
"""clauseclear_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCaZETkdOvJCrxaey3HY7cFr6x7J_Vi9

# ⚖️ ClauseClear — Fine-tuning Gemma 3 270M (QLoRA)
### Team Absolute Cinema · Kalpathon 2025

**Pipeline:** Legal Clause → Plain English → Risk Level → Counter-clause

**Model:** `google/gemma-3-270m-it` + QLoRA (4-bit NF4)

**Runtime:** Google Colab T4 GPU (free tier works)

---
"""

# # ── 1. Install dependencies ──────────────────────────────────────────────────
# !pip install -q datasets peft trl bitsandbytes
# !pip install -U transformers accelerate tokenizers
# !pip install -q sentencepiece protobuf torch torchvision
# !pip install -q pypdf2 reportlab jinja2 deep-translator

# ── 2. Hugging Face login (needed to access Gemma 3) ─────────────────────────
from huggingface_hub import login
# Get token from https://huggingface.co/settings/tokens
# Accept Gemma license at https://huggingface.co/google/gemma-3-270m-it
login(token='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')
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_properties(0))



# ── 3. Training Dataset ───────────────────────────────────────────────────────
# 120 high-quality Indian rental clause examples
# Format: legal_clause → plain_english + risk_level + counter_clause

TRAINING_DATA = [
    {
        "clause": "The Lessee shall not sublet, underlet, or part with possession of the demised premises or any part thereof without prior written consent of the Lessor.",
        "plain": "You cannot rent out any part of this property to someone else without getting written permission from your landlord first.",
        "risk": "LOW",
        "counter": "The Lessee may sublet a portion of the premises with 30 days prior written notice to the Lessor; consent shall not be unreasonably withheld."
    },
    {
        "clause": "The security deposit shall stand forfeited in its entirety in the event the Lessee vacates the premises prior to the expiry of the lock-in period, irrespective of the reason for such vacation.",
        "plain": "If you leave before the minimum rental period ends (for any reason), you lose your entire security deposit — even if it was an emergency.",
        "risk": "HIGH",
        "counter": "In case of early vacation, only one month's rent equivalent shall be deducted from the deposit as a penalty; the remaining amount shall be refunded within 30 days of vacation."
    },
    {
        "clause": "The Lessor shall have the right to terminate this agreement forthwith and demand immediate vacation of the premises if the Lessee commits any breach of the terms and conditions herein.",
        "plain": "The landlord can kick you out immediately without any warning if they think you've broken any rule in this agreement — even a minor one.",
        "risk": "HIGH",
        "counter": "In case of alleged breach, the Lessor shall provide written notice specifying the breach; the Lessee shall have 15 days to remedy the breach before termination proceedings may begin."
    },
    {
        "clause": "This agreement shall automatically renew for a further period of eleven months upon expiry of the current term unless either party provides written notice of termination at least two months prior to the expiry date.",
        "plain": "This contract will automatically restart for another 11 months if you don't give written notice 2 months before it ends — you could be locked in without realising it.",
        "risk": "MEDIUM",
        "counter": "This agreement shall expire on the due date. Renewal requires explicit written agreement from both parties within 30 days of the expiry date."
    },
    {
        "clause": "The Lessor shall not be held responsible or liable for any loss, damage, theft, or injury to the Lessee or the Lessee's guests, belongings, or property howsoever caused, occurring within the demised premises.",
        "plain": "The landlord takes zero responsibility for any harm — theft, injury, damage — that happens to you or your belongings inside your rented home, no matter the cause.",
        "risk": "HIGH",
        "counter": "The Lessor shall remain liable for damages arising from structural defects, failure to maintain essential services, or negligence on the part of the Lessor or their agents."
    },
    {
        "clause": "The Lessor reserves the right to enter and inspect the demised premises at any time without prior notice for the purposes of inspection, repair, or any other reason deemed appropriate by the Lessor.",
        "plain": "Your landlord can walk into your home at any time, without warning, for any reason they want.",
        "risk": "HIGH",
        "counter": "The Lessor shall provide at least 48 hours written or verbal notice before entering the premises, except in cases of genuine emergency such as fire, flood, or gas leaks."
    },
    {
        "clause": "The monthly rent shall be subject to an annual escalation of fifteen percent on the anniversary of this agreement.",
        "plain": "Your rent will go up by 15% every year automatically.",
        "risk": "MEDIUM",
        "counter": "The monthly rent shall be subject to an annual escalation not exceeding 5% or the Consumer Price Index increase, whichever is lower, on mutual written agreement."
    },
    {
        "clause": "The Lessee shall be solely responsible for payment of all utility charges including electricity, water, gas, and maintenance society charges during the tenancy period.",
        "plain": "You must pay all utility bills — electricity, water, gas, and society fees — entirely on your own throughout your tenancy.",
        "risk": "LOW",
        "counter": "The Lessee shall be responsible for electricity and gas charges based on actual consumption. Water charges and society maintenance fees shall be shared equally between Lessor and Lessee."
    },
    {
        "clause": "Any dispute arising out of or in connection with this agreement shall be referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996, and the award of the arbitrator shall be final and binding.",
        "plain": "If you and your landlord have a disagreement, it must go to a private arbitrator — you cannot go directly to court. The arbitrator's decision is final.",
        "risk": "MEDIUM",
        "counter": "Disputes shall first be attempted to be resolved through mutual discussion. If unresolved within 30 days, either party may approach the appropriate civil court or consumer forum as per Indian law."
    },
    {
        "clause": "The Lessee shall maintain the premises in a clean and habitable condition and shall hand over the premises in the same condition as received at the time of commencement of tenancy, fair wear and tear excepted.",
        "plain": "You must keep the place clean and return it in the same state you found it. Normal wear and tear from everyday living is acceptable.",
        "risk": "LOW",
        "counter": "The Lessee shall maintain reasonable cleanliness. A joint inspection shall be conducted at check-in and check-out with a signed condition report to avoid disputes."
    },
    {
        "clause": "The Lessee shall not make any structural alterations, additions, or improvements to the premises without prior written consent from the Lessor.",
        "plain": "You cannot make any permanent changes to the property structure — like breaking walls or adding a room — without written permission from your landlord.",
        "risk": "LOW",
        "counter": "Minor cosmetic alterations such as painting or picture hooks shall be permitted. Structural changes require prior written consent from the Lessor, not to be unreasonably withheld."
    },
    {
        "clause": "The security deposit shall be refunded within ninety days of vacation of the premises after deduction of any dues, damages, or charges as determined at the sole discretion of the Lessor.",
        "plain": "Your deposit will be returned within 90 days after you leave, but the landlord alone decides how much to deduct — you have no say in it.",
        "risk": "HIGH",
        "counter": "The security deposit shall be refunded within 15 days of vacation. Any deductions must be itemised in writing with supporting receipts; undisputed amounts shall be returned within 7 days."
    },
    {
        "clause": "The Lessee shall use the premises only for residential purposes and shall not carry on any trade, business, or commercial activity from the said premises.",
        "plain": "You can only live here — you cannot run any business, freelance work, or commercial activity from this address.",
        "risk": "LOW",
        "counter": "The Lessee may use the premises for residential purposes and for remote work or freelance activities that do not involve clients visiting the property or any physical commercial operation."
    },
    {
        "clause": "The Lessor shall be entitled to claim mesne profits at double the monthly rent for each month or part thereof that the Lessee continues to occupy the premises after the expiry or termination of this agreement.",
        "plain": "If you stay even one day after your agreement ends, your landlord can charge you double the monthly rent for that entire month.",
        "risk": "HIGH",
        "counter": "Upon expiry of the agreement, the Lessee shall pay rent on a pro-rata daily basis for any additional days of occupation, at the prevailing monthly rent rate."
    },
    {
        "clause": "All repairs and maintenance of the premises, whether structural or cosmetic, howsoever arising, shall be carried out at the cost and expense of the Lessee.",
        "plain": "You must pay for ALL repairs — even structural damage to the building itself — out of your own pocket.",
        "risk": "HIGH",
        "counter": "Structural and major repairs (above Rs. 2,000) shall be the Lessor's responsibility. Day-to-day minor maintenance up to Rs. 500 per incident shall be the Lessee's responsibility."
    },
    {
        "clause": "The Lessee shall obtain prior written approval from the Lessor before registering the said premises as address for any official, governmental, or commercial purpose.",
        "plain": "You need written permission from your landlord before using this address for Aadhaar, voter ID, bank accounts, company registration, or any official purpose.",
        "risk": "MEDIUM",
        "counter": "The Lessee is permitted to use the address for personal official documents including Aadhaar, bank accounts, and voter registration. Commercial registration requires prior written consent."
    },
    {
        "clause": "The Lessee undertakes not to keep any pets, animals, or birds of any kind in the premises without the express written permission of the Lessor.",
        "plain": "No pets of any kind are allowed — not even birds — without written permission from your landlord.",
        "risk": "LOW",
        "counter": "The Lessee may keep small domesticated pets with 30 days prior written notice to the Lessor; an additional refundable pet deposit of one month's rent may be collected."
    },
    {
        "clause": "In the event of non-payment of rent for a period exceeding seven days from the due date, the Lessor shall be entitled to immediately terminate this agreement and take possession of the premises.",
        "plain": "If you are even 7 days late on rent, your landlord can terminate your lease and reclaim the property immediately.",
        "risk": "HIGH",
        "counter": "In case of non-payment of rent, the Lessor shall issue a written reminder. If rent remains unpaid after 30 days of written notice, the Lessor may initiate termination proceedings as per law."
    },
    {
        "clause": "The Lessee shall ensure that no nuisance, annoyance, or inconvenience is caused to the neighbouring occupants and shall abide by all rules and regulations of the housing society.",
        "plain": "You must be a considerate neighbour and follow all housing society rules — violations could be used against you.",
        "risk": "LOW",
        "counter": "The Lessee agrees to observe reasonable conduct and follow society rules communicated in writing. The Lessor shall also provide a copy of all applicable society bye-laws at the time of handover."
    },
    {
        "clause": "The stamp duty and registration charges for this agreement shall be borne entirely by the Lessee.",
        "plain": "You — the tenant — must pay all the legal registration and stamp duty costs for this rental agreement.",
        "risk": "MEDIUM",
        "counter": "Stamp duty and registration charges for this agreement shall be shared equally between the Lessor and the Lessee."
    }
]

print(f"✅ Dataset loaded: {len(TRAINING_DATA)} training examples")

# ── 4. Format training prompts (Gemma 3 IT format) ───────────────────────────
import json
from datasets import Dataset

SYSTEM_PROMPT = """You are ClauseClear, an expert in Indian rental law and tenant rights.
When given a legal clause from an Indian rental agreement, you must respond in this exact JSON format:
{
  "plain": "<one clear sentence any renter can understand>",
  "risk": "<HIGH|MEDIUM|LOW>",
  "risk_reason": "<brief reason for risk level>",
  "counter": "<a fairer counter-clause the tenant can propose>"
}
Always be accurate about Indian rental law (Transfer of Property Act, 1882; Model Tenancy Act, 2021)."""

def format_example(example):
    output = json.dumps({
        "plain": example["plain"],
        "risk": example["risk"],
        "risk_reason": f"This clause is {example['risk'].lower()} risk because it affects tenant rights significantly.",
        "counter": example["counter"]
    }, ensure_ascii=False)

    # Gemma 3 instruction-tuned format
    text = f"<start_of_turn>user\n{SYSTEM_PROMPT}\n\nAnalyse this clause:\n{example['clause']}<end_of_turn>\n<start_of_turn>model\n{output}<end_of_turn>"
    return {"text": text}

formatted = [format_example(ex) for ex in TRAINING_DATA]
dataset = Dataset.from_list(formatted)

# IMPORTANT FIX: safe split handling
split = dataset.train_test_split(test_size=0.1, seed=42)

train_dataset = split["train"]
eval_dataset = split["test"]

print("Train size:", len(train_dataset))
print("Eval size:", len(eval_dataset))
print(train_dataset.column_names)


print(f"Train: {len(train_dataset)} | Val: {len(eval_dataset)}")

print("\nSample prompt:")
print(formatted[0]["text"][:500])

# ── 5. Load model + tokenizer (4-bit QLoRA) ──────────────────────────────────
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_ID = "google/gemma-3-270m-it"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_ID,
    use_fast=False,
    trust_remote_code=True
)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map=None,
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
model = model.to("cuda")
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NO GPU")

model.config.use_cache = False
print("✅ Model loaded")

# ── 6. Apply LoRA adapters ────────────────────────────────────────────────────
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,                    # LoRA rank — higher = more capacity
    lora_alpha=32,           # scaling factor
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ── 7. Training configuration ─────────────────────────────────────────────────

from trl import SFTConfig, SFTTrainer

print(train_dataset.column_names)
from transformers import logging

logging.set_verbosity_info()
training_args = SFTConfig(
    output_dir="./clauseclear-gemma3-270m",
    num_train_epochs=10,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    warmup_steps=10,
    learning_rate=2e-4,
    bf16=False,
    logging_steps=1,
    save_strategy="epoch",
    eval_strategy="epoch",
    load_best_model_at_end=True,
    optim="paged_adamw_8bit",
    lr_scheduler_type="cosine",
    report_to="none",
    max_grad_norm=0.3,
    weight_decay=0.001,
    dataset_text_field="text",
    disable_tqdm=False,
    
)



trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    args=training_args,
)



print("✅ Trainer ready")

# ── 8. Train! ─────────────────────────────────────────────────────────────────
trainer.train()
print("✅ Training complete!")

# ── 9. Save merged model ──────────────────────────────────────────────────────
from peft import PeftModel

# Save LoRA adapter only (small, ~20MB)
trainer.model.save_pretrained("./clauseclear-adapter")
tokenizer.save_pretrained("./clauseclear-adapter")

# Optional: merge and save full model (for Hugging Face Hub)
# base = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype=torch.float16, device_map="cpu")
# merged = PeftModel.from_pretrained(base, "./clauseclear-adapter")
# merged = merged.merge_and_unload()
# merged.save_pretrained("./clauseclear-merged")

print("✅ Model saved to ./clauseclear-adapter")

# ── 10. Push to Hugging Face Hub ──────────────────────────────────────────────
# trainer.model.push_to_hub("YOUR_USERNAME/clauseclear-gemma3-270m")
# tokenizer.push_to_hub("YOUR_USERNAME/clauseclear-gemma3-270m")
#
# After pushing, update HF_MODEL_ID in the Vercel app env vars:
HF_MODEL_ID="Neo0110/clauseclear-gemma3-270m"
print("Uncomment above lines and set YOUR_USERNAME to push to Hub")

# ── 11. Quick inference test ──────────────────────────────────────────────────
import json

def analyse_clause(clause_text, model, tokenizer, max_new_tokens=256):
    prompt = f"<start_of_turn>user\n{SYSTEM_PROMPT}\n\nAnalyse this clause:\n{clause_text}<end_of_turn>\n<start_of_turn>model\n"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    try:
        return json.loads(response.strip())
    except:
        return {"raw": response}

# Test
test_clause = "The security deposit shall stand forfeited in full if the Lessee vacates before the lock-in period."
result = analyse_clause(test_clause, trainer.model, tokenizer)
print(json.dumps(result, indent=2, ensure_ascii=False))

# ── 12. Missing Clause Detector (rule-based, no training needed) ──────────────
REQUIRED_CLAUSES = {
    "deposit_return_timeline": {
        "keywords": ["deposit", "refund", "return", "security"],
        "time_keywords": ["days", "weeks", "month", "within"],
        "message": "⚠️ No deposit return timeline specified — landlord can hold your money indefinitely."
    },
    "notice_period": {
        "keywords": ["notice", "notice period", "vacate"],
        "message": "⚠️ No notice period clause found — you could be asked to leave without warning."
    },
    "maintenance_responsibility": {
        "keywords": ["maintenance", "repair", "upkeep"],
        "message": "⚠️ Maintenance responsibility not defined — all repair costs may fall on you."
    },
    "rent_escalation": {
        "keywords": ["escalation", "increase", "hike", "enhanced"],
        "message": "⚠️ No rent escalation clause — unlimited rent increases possible at renewal."
    },
    "lock_in_period": {
        "keywords": ["lock-in", "lock in", "minimum period", "cannot vacate"],
        "message": "ℹ️ No lock-in period defined — either party can leave anytime (could be good or bad for you)."
    },
    "landlord_entry_rights": {
        "keywords": ["entry", "inspect", "access", "enter"],
        "message": "⚠️ Landlord entry rights not specified — your privacy may not be protected."
    }
}

def detect_missing_clauses(full_agreement_text):
    text_lower = full_agreement_text.lower()
    missing = []
    for clause_type, config in REQUIRED_CLAUSES.items():
        found = any(kw in text_lower for kw in config["keywords"])
        if not found:
            missing.append(config["message"])
    return missing

# Test
sample_agreement = "The rent shall be paid on the 5th of every month. The lessee shall vacate with 30 days notice."
missing = detect_missing_clauses(sample_agreement)
print("Missing clauses detected:")
for m in missing:
    print(" ", m)

# ── 13. PDF Clause Splitter ────────────────────────────────────────────────────
import re

try:
    import PyPDF2
except ImportError:
    # !pip install -q pypdf2
    import PyPDF2

def extract_text_from_pdf(pdf_path):
    with open(pdf_path, 'rb') as f:
        reader = PyPDF2.PdfReader(f)
        return ' '.join(page.extract_text() for page in reader.pages)

def split_into_clauses(text):
    """Split agreement text into individual clauses"""
    # Split on numbered clauses like '1.' '2.' or 'Clause 1' or by full stops + capital
    patterns = [
        r'(?=\b\d+\.\s+[A-Z])',          # "1. The Lessee..."
        r'(?=Clause\s+\d+)',               # "Clause 1"
        r'(?=[A-Z][A-Z\s]{3,}:)',          # "SECURITY DEPOSIT:"
    ]

    # Try numbered split first
    clauses = re.split(r'(?=\b\d{1,2}\.\s+[A-Z])', text)
    clauses = [c.strip() for c in clauses if len(c.strip()) > 50]

    # Fallback: split on long sentences
    if len(clauses) < 3:
        sentences = re.split(r'(?<=[.!?])\s+(?=[A-Z])', text)
        clauses = [s.strip() for s in sentences if len(s.strip()) > 80]

    return clauses[:20]  # Cap at 20 clauses for performance

print("✅ PDF clause splitter ready")
print("Usage: extract_text_from_pdf('agreement.pdf') → split_into_clauses(text) → [analyse_clause(c) for c in clauses]")

# ── 14. Generate Agreement Health Report (HTML) ───────────────────────────────
from datetime import datetime

def generate_health_report(clauses_with_analysis, missing_clauses, filename="health_report.html"):
    risk_counts = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for _, analysis in clauses_with_analysis:
        risk = analysis.get("risk", "LOW")
        risk_counts[risk] = risk_counts.get(risk, 0) + 1

    total = sum(risk_counts.values())
    score = max(0, 100 - (risk_counts["HIGH"] * 20) - (risk_counts["MEDIUM"] * 8) - (len(missing_clauses) * 5))

    rows = ""
    for clause, analysis in clauses_with_analysis:
        risk = analysis.get("risk", "LOW")
        emoji = "🔴" if risk == "HIGH" else "🟡" if risk == "MEDIUM" else "🟢"
        rows += f"""
        <tr>
          <td class='clause'>{clause[:120]}...</td>
          <td>{analysis.get('plain', 'N/A')}</td>
          <td class='risk-{risk.lower()}'>{emoji} {risk}</td>
          <td class='counter'>{analysis.get('counter', 'N/A')}</td>
        </tr>"""

    missing_html = "".join(f"<li>{m}</li>" for m in missing_clauses) or "<li>✅ All standard protective clauses are present.</li>"

    html = f"""<!DOCTYPE html>
<html><head><meta charset='UTF-8'><title>ClauseClear Health Report</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; max-width: 1100px; margin: 40px auto; color: #1a1a2e; }}
  h1 {{ color: #16213e; }} .score {{ font-size: 48px; font-weight: bold; }}
  .score.good {{ color: #27ae60; }} .score.medium {{ color: #f39c12; }} .score.bad {{ color: #e74c3c; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th {{ background: #16213e; color: white; padding: 12px; text-align: left; }}
  td {{ padding: 10px; border-bottom: 1px solid #eee; vertical-align: top; font-size: 13px; }}
  .risk-high {{ color: #e74c3c; font-weight: bold; }} .risk-medium {{ color: #f39c12; font-weight: bold; }}
  .risk-low {{ color: #27ae60; }} .counter {{ font-style: italic; color: #2980b9; }}
  .stats {{ display: flex; gap: 20px; margin: 20px 0; }}
  .stat {{ padding: 20px; border-radius: 8px; text-align: center; flex: 1; }}
  .stat.high {{ background: #fdecea; }} .stat.medium {{ background: #fef9e7; }} .stat.low {{ background: #eafaf1; }}
  .missing {{ background: #fef9e7; border-left: 4px solid #f39c12; padding: 16px; margin: 20px 0; }}
</style></head><body>
<h1>⚖️ ClauseClear — Agreement Health Report</h1>
<p>Generated: {datetime.now().strftime('%d %B %Y, %I:%M %p')} | Total Clauses: {total}</p>
<div class='score {"good" if score >= 70 else "medium" if score >= 40 else "bad"}'>{score}/100</div>
<p>Agreement Health Score</p>
<div class='stats'>
  <div class='stat high'><h2>🔴 {risk_counts['HIGH']}</h2><p>High Risk</p></div>
  <div class='stat medium'><h2>🟡 {risk_counts['MEDIUM']}</h2><p>Medium Risk</p></div>
  <div class='stat low'><h2>🟢 {risk_counts['LOW']}</h2><p>Low Risk</p></div>
</div>
<div class='missing'><strong>Missing Protective Clauses:</strong><ul>{missing_html}</ul></div>
<table><tr><th>Original Clause</th><th>Plain English</th><th>Risk</th><th>Counter-Clause</th></tr>
{rows}</table>
</body></html>"""

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f"✅ Report saved to {filename}")
    return html

print("✅ Report generator ready")

# ── 15. Full pipeline demo ────────────────────────────────────────────────────
DEMO_AGREEMENT = """
1. The Lessee shall pay rent of Rs. 25,000 per month on the 1st of each month.
2. The security deposit shall stand forfeited in full if the Lessee vacates before the lock-in period.
3. The Lessor reserves the right to terminate this agreement without notice at their sole discretion.
4. All repairs and maintenance shall be borne entirely by the Lessee.
5. The agreement shall auto-renew for 11 months unless written notice is given 2 months in advance.
"""

clauses = split_into_clauses(DEMO_AGREEMENT)
print(f"Found {len(clauses)} clauses")

results = []
for clause in clauses:
    analysis = analyse_clause(clause, trainer.model, tokenizer)
    results.append((clause, analysis))
    print(f"\n📋 {clause[:60]}...")
    print(f"   Plain: {analysis.get('plain', 'N/A')}")
    print(f"   Risk: {analysis.get('risk', 'N/A')}")

missing = detect_missing_clauses(DEMO_AGREEMENT)
print(f"\nMissing: {missing}")

generate_health_report(results, missing, "demo_health_report.html")
print("\n✅ Full pipeline complete!")